---
- name: "Install iptables-services"
  yum:
   name: iptables-services
   state: present
  notify: "Enable iptables-services"
  tags:
   - iptables

- name: "Place config to server"
  template:
   src: "iptables.j2"
   dest: "/etc/sysconfig/iptables"
   validate: "iptables-restore --test %s"
  when: iptables is defined
  notify: "Restart iptables"
  tags:
   - iptables
