---
- name: "Enable iptables-services"
  systemd:
   name: iptables
   enabled: true
   daemon-reload: true
   state: started
  tags:
   - iptables

- name: "Restart iptables"
  systemd:
   name: iptables
   enabled: true
   daemon-reload: true
   state: restarted
  tags:
   - iptables
